Add testnets support to discovery
l2beat/tools pull request #111
Opened 2024-01-10 10:57 UTC by michalsidzej

It's sometimes useful to run discovery on the testnet. We need it in lz-monitoring to work on the v2 contracts.

2024-01-10 12:23 UTC, sdlyy requested changes

2024-01-10 12:23 UTC, sdlyy commented on packages/discovery/src/config/config.discovery.ts
> +          'DISCOVERY_SEPOLIA_RPC_GETLOGS_MAX_RANGE',
```suggestion
      return {
        chainId: ChainId.GOERLI,
        rpcUrl: env.string('DISCOVERY_GOERLI_RPC_URL'),
        rpcGetLogsMaxRange: env.optionalInteger(
          'DISCOVERY_GOERLI_RPC_GETLOGS_MAX_RANGE',
```

2024-01-11 12:59 UTC, sdlyy approved these changes

2024-01-17 14:58 UTC, mateuszradomski approved these changes

2024-03-18 09:23 UTC, merged